### ISSUE TITLE
创建demo也需要拿到权限吗？

### ISSUE THREAD

**Issue by sunny-Fung** [hiloteam/Sein.js#12]
![image](https://user-images.githubusercontent.com/26086299/93201364-a89f2580-f783-11ea-8f39-d10b1432d891.png)
跟着development的步骤走，然后就报错了，想问下是操作不当吗？还是其他原因？

**Comment by 06wj** [comment]
git配置问题吧 https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by LeoEatle** [comment]
这大概率是自己用了http方式去clone，而submodule都是ssh链接的原因吧
