### ISSUE TITLE
关于Sein.js的一些建议

### ISSUE THREAD

**Issue by sbfkcel** [hiloteam/Sein.js#5]
- 增加编辑器支持，例如：playcanvas
  - 粒子生成工具
  - 集成相关优化工具
     - 模型面减少工具
  - shader 编辑工具（可参考的shaderForge）
- 抛弃webpack、jsx，原来前端的优势就是无编译，因为要工程化搞出了这个么东西。开发体验极差，特别是项目大的时候编译效率极低。电脑资源占用直接满载，热到爆~~
- 高性能密集运算模块使用wasm，必境JS还是受限于引擎本身的诸多限制

**Comment by dtysky** [comment]
你好。

1. 每个引擎都有自己的取舍，最终选择了Unity而非WebEditor作为场景编辑器是由我们的取舍的。
2. 粒子编辑器阿里内部有一套对应的工具，对外后续可能计划实现Unity粒子系统的子集。
2. 优化工具后续会计划在Unity扩展中集成，包括Static Batch。
3. Shader编辑工具这个对于我们的目标应用并不急迫，我们目前还是以解决应用重点痛点为导向的。
4. Webpack正是前端的某种优势所在，目前前端开发的构建流程是不可避免的，尤其是这种需要处理大量资源的工程。
5. 我们已有一些探索，模型解压缩默认使用wasm，数学库也有探索：[gl-matrix-wasm](https://github.com/dtysky/gl-matrix-wasm)，并计划探索SIMD，但尚未达到理想（JIT后的JS也很快了），后续还要继续研究。
6. WebGPU我们在等待浏览器支持，基本技术探索已经到位。

**Comment by sbfkcel** [comment]
不过编辑器使用Unity，又要编译。跟Project Tiny相比完全没有任何的优势。

Project Tiny完美享受Unity的整个生态和工具链接，全字节码运行速度上肯定是碾压的。

JIT再快，在处理千万级顶点模型渲染的时候。提供一点都是压倒性的。

脚本语言最大的好处就是不编译。

**Comment by dtysky** [comment]
> 不过编辑器使用Unity，又要编译。跟Project Tiny相比完全没有任何的优势。
> 
> Project Tiny完美享受Unity的整个生态和工具链接，全字节码运行速度上肯定是碾压的。
> 
> JIT再快，在处理千万级顶点模型渲染的时候。提升一点点运算能力在这么大的规模面前都是压倒性的。
> 
> PS：脚本语言最大的好处就是不编译。

如果Unity的TinyMode可以满足你的诉求，建议你使用Tiny，我们的目标不是取代Unity，也做不到。

至于编译构建工程化这个见仁见智吧，尊重你的想法。

PS : 顶点多主要考察的是GPU硬件性能吧…和CPU这边JIT不JIT有啥关系…你说节点多我还能理解。

**Comment by sbfkcel** [comment]
感谢解答。
---
抱歉，说错。是『节点』~~

毕境目前webgame瓶颈很大一部分还是在于性能上嘛。

虽然看你们暂时不打算有WebEditor支持，但还是期待有朝一日可以支持。毕境那些端的编辑器太重了。

对 Sein.js 表示持续关注。希望能成功webgame完整的all in one解决方案。
