### ISSUE TITLE
运行npm run dev 报错

### ISSUE THREAD

**Issue by highmind** [hiloteam/Sein.js#6]
![QQ截图20200721174257](https://user-images.githubusercontent.com/19481942/88039135-c41df380-cb79-11ea-873b-c5ccdb8c9772.png)

**Comment by highmind** [comment]
ERROR in ./src/assets/gltfs/miku.gltf
Module build failed (from ./node_modules/seinjs-gltf-loader/lib/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: ENOENT: no such file or directory, mkdir 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp-125285AdzmA2m7KAr\D:\wamp64\www\sein3d\src\assets\gltfs

**Comment by dtysky** [comment]
已解决，请更新seinjs-gltf-loader到0.9.28

https://github.com/hiloteam/seinjs-gltf-loader/issues/2

**Comment by highmind** [comment]
> 已解决，请更新seinjs-gltf-loader到0.9.28
> 
> [hiloteam/seinjs-gltf-loader#2](https://github.com/hiloteam/seinjs-gltf-loader/issues/2)

多谢
