### ISSUE TITLE
请问在哪里可以找到官网的开始页面中的3d模型

### ISSUE THREAD

**Issue by YoshieraHuang** [hiloteam/Sein.js#7]
我是一个特别新的新人，想跟着开始的教程做一遍，但是其中的地球，飞机等3d模型不知道在哪里获得。

**Comment by 06wj** [comment]
可以参考下这个仓库 https://github.com/hiloteam/seinjs-tutorial-develeper

**Comment by YoshieraHuang** [comment]
3Q！
